-- Enum tables

CREATE TABLE IF NOT EXISTS JOB_TITLES (
	job_id INTEGER PRIMARY KEY,
	job_title TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS CROP_TYPES (
	crop_id INTEGER PRIMARY KEY,
	crop_name TEXT UNIQUE NOT NULL
);

-- Entities

CREATE TABLE IF NOT EXISTS  CROP_SILOS (
	crop_silo_id INTEGER PRIMARY KEY,
	crop_type_id INTEGER NOT NULL,
	FOREIGN KEY (crop_type_id) REFERENCES CROP_TYPES(crop_id)
);

CREATE TABLE IF NOT EXISTS FARMLANDS (
	farmland_id INTEGER PRIMARY KEY,
	farmland_size INTEGER NOT NULL,
	crop_type_id INTEGER NOT NULL,
	overseer_id INTEGER NOT NULL,
	FOREIGN KEY (crop_type_id) REFERENCES CROP_TYPES(crop_id),
	FOREIGN KEY (overseer_id) REFERENCES EMPLOYEES(emp_id)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
	emp_id INTEGER PRIMARY KEY,
	first_name TEXT NOT NULL,
	middle_name TEXT DEFAULT 'N/A' NOT NULL,
	last_name TEXT NOT NULL,
	job_title_id INTEGER NOT NULL,
	FOREIGN KEY (job_title_id) REFERENCES JOB_TITLES(job_id)
);
